services:
  xray-logger-agent:
    image: likstanov/xray-logger-agent:latest
    container_name: xray_logger_agent
    restart: always
    env_file:
      - .env
    volumes:
      - ${ACCESS_LOG_PATH}:${ACCESS_LOG_PATH}:ro
    network_mode: bridge